Object.assign($App,{request:{
account: function(callback) {
	//console.log('App.request.account');
	var apiurl = $App.api.service('auth').location+'account/';
	return new Promise(function(resolve, reject){
		XHR.request(apiurl,function(data){resolve(data)});
	});
},
archive: function(callback){
	var apiurl = $App.api.service('user_data').location;
	apiurl+= 'cloud/telecasts/?method=list&format=json';
	XHR.request(apiurl, this._archive.bind(this, callback));
	console.log('request archive', apiurl);
},
_archive: function(callback, data, xhr) {
	console.log(data);
	var list = (data ? data.elements : []).map(v=>{
		var attr = v.attributes;
		//if(!attr.autogenerated_id) return v.id;
		//else return attr.catalogue_item_id;
		return attr.catalogue_item_id;
	});
	callback(list);
},
favourites: function(callback){
	var apiurl = $App.api.service('user_data').location;
	apiurl+= 'favourites/tv/channels/?method=list&format=json';
	XHR.request(apiurl, this._favourites.bind(this, callback));
	console.log('request favourites', apiurl);
},
_favourites: function(callback, data, xhr) {
	console.log(data);
	var list = (data ? data.elements : []).map(v=>{
		var attr = v.attributes;
		//if(!attr.autogenerated_id) return v.id;
		//else return attr.catalogue_item_id;
		return attr.catalogue_item_id;
	});
	callback(list);
}
}});